const VERTICAL_AMOUNT = 9;
const HORIZON_AMOUNT = 16;
const UNIQUE = 43;
const TILE_SIZE = 48;
const TILE_SPACE = 8;
const REMOVE_DELAY_MILLIS = 200;
const PAIR_AMOUNT = (HORIZON_AMOUNT * VERTICAL_AMOUNT) / 2;
export { VERTICAL_AMOUNT, HORIZON_AMOUNT, UNIQUE, PAIR_AMOUNT, TILE_SIZE, TILE_SPACE, REMOVE_DELAY_MILLIS, };
