const VERTICAL_AMOUNT: number = 9;
const HORIZON_AMOUNT: number = 16;
const UNIQUE: number = 36;

const TILE_SIZE = 48;
const TILE_SPACE = 8;

const REMOVE_DELAY_MILLIS = 350;

const PAIR_AMOUNT: number = (HORIZON_AMOUNT * VERTICAL_AMOUNT) / 2;

export { VERTICAL_AMOUNT, HORIZON_AMOUNT, UNIQUE, PAIR_AMOUNT, TILE_SIZE, TILE_SPACE, REMOVE_DELAY_MILLIS }